parameters:
  name: ""

steps:
- task: CopyFiles@2
  inputs:
    contents: '$(System.DefaultWorkingDirectory)/terraform/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Terraform Artifact'
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/terraform' 
    artifactName: 'terraform'