parameters:
  name: ""
  environment: ""
  containerName: ""
  connectedService: ""
  service_plan_tier: "Basic"
  service_plan_size: "B1"

steps:
  - download: current
    displayName: "Download Terraform Artifact"
    artifact: "terraform"
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: "Replace Terraform Vars"
    inputs:
      rootDirectory: "$(Pipeline.Workspace)/terraform"
      targetFiles: "**/*.tf*"
      encoding: "auto"
      writeBOM: true
      actionOnMissing: "warn"
      keepToken: false
      tokenPrefix: "__"
      tokenSuffix: "__"

  - task: TerraformInstaller@0
    displayName: "Install Terraform"
    inputs:
      terraformVersion: "latest"
  - script: |
      az login --service-principal -u $(sp_client_id) -p $(sp_client_secret) --tenant $(tenant_id)
      terraform init -upgrade
      terraform workspace new ${{ parameters.environment }}
      terraform workspace select ${{ parameters.environment }}
      terraform plan  -out=deploy.tfplan
      terraform apply -auto-approve -var-file="./tfvars/${{ parameters.environment }}.tfvars"
    workingDirectory: "$(Pipeline.Workspace)/terraform"
    displayName: Terraform