name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configuración de Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Paso 3: Autenticación en Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Paso 4: Cambiar al directorio de Terraform (si es necesario)
      # Si los archivos .tf están en una subcarpeta llamada 'terraform', habilita este paso
      - name: Change to Terraform directory
        run: cd terraform

      # Paso 5: Inicializar Terraform
      - name: Initialize Terraform
        run: terraform init

      # Paso 6: Validar el código de Terraform
      - name: Validate Terraform
        run: terraform validate

      # Paso 7: Planificar los cambios
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Paso 8: Aplicar los cambios
      - name: Terraform Apply
        run: terraform apply -input=false tfplan