name: Deploy Terraform to Azure

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Listar archivos en el directorio actual (para depuración)
      - name: List files in current directory
        run: ls -la

      # Paso 3: Configuración de Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Paso 4: Autenticación en Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Paso 5: Inicializar Terraform (si los archivos están en un subdirectorio, usa -chdir)
      - name: Initialize Terraform
        run: terraform -chdir=terraform init

      # Paso 6: Validar el código de Terraform
      - name: Validate Terraform
        run: terraform -chdir=terraform validate

      # Paso 7: Planificar los cambios
      - name: Terraform Plan
        run: terraform -chdir=terraform plan -out=tfplan

      # Paso 8: Aplicar los cambios
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -input=false tfplan